name: PR Tests

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v4

    - name: Construir y levantar contenedores de Docker
      run: |
        docker compose build
        docker compose up -d
        sleep 15

    - name: Ejecutar tests y comprobar cobertura (>80%)
      run: |
        docker compose exec -T web coverage run manage.py test
        docker compose exec -T web coverage report --fail-under=80