name: PR Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Levantar Docker
        run: |
          docker compose up -d --build
          sleep 20

      - name: Tests y Cobertura
        run: |
          docker compose exec -T web coverage run manage.py test
          docker compose exec -T web coverage report --fail-under=80